modLoader="javafml" 
loaderVersion="[38,)" 
license="MIT License"

issueTrackerURL="https://github.com/989onan/CarPetsMod/issues"

[[mods]] 
modId="followingcarmod" 
version="${file.jarVersion}"
displayName="FollowingCarMod"

displayURL="https://www.curseforge.com/minecraft/mc-mods/car-pets" #optional
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="followingcaricon.png"

#needed so that people know when to update
updateJSONURL= "https://raw.githubusercontent.com/989onan/CarPetsMod/main/updates.json"


credits="Myself of course. Oh yeah, and Tablua for model making: https://www.curseforge.com/minecraft/mc-mods/tabula-minecraft-modeler. Also Mazzy: https://www.deviantart.com/mazdatiger Fumei:https://www.deviantart.com/moozdamilfshake Amari,Jane,TIFF:989onan Kodachi:Kodachi"
authors="989onan"


description='''
This mod was made by 989onan#0794. This is my first mod, but it is massively improving.
I made this as my many other strange mods to satisfy my needs of making random crap involving cars.
Enjoy?
Also contact me on discord if you want the source code to try to make your own mod. It's also on the original mod page! :P

ORIGINAL MOD PAGE. IF THIS WAS DOWNLOADED ON ANOTHER WEBSITE (excluding from me personally), IT IS STOLEN!
https://www.curseforge.com/minecraft/mc-mods/car-pets
'''


[[dependencies.followingcarmod]]
    modId="forge"
    mandatory=true
    versionRange="[38,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.followingcarmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"
